### ISSUE TITLE
Why is .vscode included in git?

### ISSUE THREAD

**Issue by tailaiw** [faustomorales/python-boilerplate#2]
Is there a intentional reason why .vscode is included in the git? I usually gitignore my .vscode directory as i feel it is something more a personal choice and others may have different preferences from mine. But I do notice your only setting there right now is on python path, so I’m not sure if it is something related to your docker environment and you want to enforce it?

**Comment by faustomorales** [comment]
Good question! tl;dr: I removed it just now. It wasn't really necessary and actually created some problems.

I had included it because it had the setting pointing to the local `.venv` that is created if you choose to run `make init`. But, working with a friend, I learned that this does not transfer to Windows and so it makes the repository less portable. And Visual Studio code seems to be pretty good at noticing the `.venv` folder when it is created and adjusting accordingly. So I took out the `.vscode` folder just now using b9b91a60f3057d329ccc5079c85306c2cc568de7. I'm also going to need to make more changes at some point to improve Windows support in the `Makefile` but I'll open a separate issue for that.
